server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa12358@jiy
    type: com.alibaba.druid.pool.DruidDataSource
 
mybatis-plus:
  mapper-locations: classpath:com/haust/mapper/*.xml  type-aliases-package: com.haust.entity